version: '3'
services:
  my_app:
    image: php-fpm-8.2
    container_name: my_app_emeralpha
    volumes:
      - .:/var/www/app
      - ~/.composer:/root/.composer
      - .docker/php-fpm/php.ini:/usr/local/etc/php/conf.d/php.ini
    ports:
      - 9100:9000
    depends_on:
      - mysql
    working_dir: /var/www/app
  mysql:
    image: mysql:latest
    container_name: my_app_emeralpha_mysql
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "7001:80"
    environment:
      PMA_ARBITRARY: 1
  nginx:
    image: nginx
    container_name: my_app_emeralpha_nginx
    #restart: on-failure
    depends_on:
      - my_app
    working_dir: /var/www
    ports:
      - "8080:80"
    volumes:
      - .docker/nginx/sites/app.conf:/etc/nginx/conf.d/default.conf
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www/app
networks:
  default:
    external: true
    name: net-docker

#docker-compose -f docker-compose-dev.yml -p emeralphaai up -d
